spring:
  datasource:
    url:jdbc:mysql://localhost:3306/heroku_f3d0422501771cc?useSSL=false
    username:b18e6e1da00334
    password:b9819350

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  #The SQL dialect makes Hibernate generate better SQL for the chosen database
  # jpa:
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#JPA Settings
  # jpa.hibernate.ddl_auto: create
